In [2]:
import pandas as pd

In [10]:
pd.read_csv("/Users/ajokeogunlolu/Desktop/Data Analytics /CovidDeaths1.csv")

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,03/01/2020,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,04/01/2020,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,05/01/2020,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,06/01/2020,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,07/01/2020,41128772,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351811,ZWE,Africa,Zimbabwe,21/10/2023,16320539,265821.0,0.0,1.857,5720.0,0.0,...,0.009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351812,ZWE,Africa,Zimbabwe,22/10/2023,16320539,265821.0,0.0,1.857,5720.0,0.0,...,0.009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351813,ZWE,Africa,Zimbabwe,23/10/2023,16320539,265821.0,0.0,1.857,5720.0,0.0,...,0.009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351814,ZWE,Africa,Zimbabwe,24/10/2023,16320539,265821.0,0.0,0.000,5720.0,0.0,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351815,ZWE,Africa,Zimbabwe,25/10/2023,16320539,265821.0,0.0,0.000,5720.0,0.0,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN